### ISSUE TITLE
Collaboration with `ethsnarks`

### ISSUE THREAD

**Issue by HarryR** [gnosis/dex-zksnarks#2]
Hi,

I'm working on a project called `ethsnarks`: https://github.com/HarryR/ethsnarks

The goal of this project is to create easy to integrate components and on-chain contracts for reusable SNARK circuits, e.g. any project wishing to have a '1 of N' commitment (like a ring signature), can use the `ethsnarks` component for it which provides both on-chain and off-chain components (with WebAssembly support, native DLL, python/nodejs wrappers etc.).

 I really like the idea of a decentralised exchange using zkSNARKs, and I think it would be worthwhile exchanging ideas about what the problems are, how to deploy this stuff etc.

**Comment by fleupold** [comment]
Will reach out via e-mail.
